debug: false

bobcatAddress: 192.168.1.55
intervalSeconds: 20

mqtt:
  enabled: true
  server: mq.ninefives.wtf
  port: 1883
  username: username
  password: Assword12345
  clientId: bobcat-monitor
  topicRoot: bobcat-monitor